################################################################################
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: OTHER
# SPDX-FileCopyrightText: (c) 2021, The Raetro authors and contributors
################################################################################
name: "Feature Request"
description: "Suggest a new feature or other enhancement."
title: 'Title of your Feature Request'
labels:
  - enhancement
assignees:
  - boogermann
body:
  - type: markdown
    attributes:
      value: |
        Hi there,

        Please note that we try to keep the issue tracker reserved for bug reports and feature requests.
        Make sure to [search for existing feature requests](https://github.com/raetro/mimic_firmware/issues?q=label%3Aenhancement) before filing a new one!

        For general usage questions, please visit the user guide at [Rætro.Docs](https://docs.raetro.org/mimic-nsx).

  - type: input
    id: current_version
    attributes:
      label: MiMiC NSX version (or build number)
      placeholder: "0.1.1, 1.0.3-fb597ed"
      description: |
        Open the about menu to show the version, and write the version here.
        This will record which version was current at the time of your feature request, to help manage the request backlog.

        If you're not using the latest version, please check to see if something related to your request has already been implemented in a later version.
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use-cases
      description: |
        In order to properly evaluate a feature request, it is necessary to understand the use-cases for it.

        Please describe below the end goal you are trying to achieve that has led you to request this feature.
      placeholder: |
        Please keep this section focused on the problem and not on the suggested solution. We'll get to that in a moment, below!
    validations:
      required: true

  - type: textarea
    id: attempted_solutions
    attributes:
      label: Attempted Solutions
      description: |
        If you've already tried to solve the problem within MiMiC - I/O Controller's existing features and
        found a limitation that prevented you from succeeding, please describe it below in as much detail as possible.

        Ideally, this would include real configuration snippets that you tried, command lines you ran, and what results you got in each case.
      placeholder: |
        Please remove any sensitive information such as passwords before sharing configuration snippets and command lines.
    validations:
      required: false

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        If you have an idea for a way to address the problem via a change to MiMiC features, please describe it below.

        In this section, it's helpful to include specific examples of how what you are suggesting might look in configuration files,
        or on the command line, since that allows us to understand the full picture of what you are proposing.

      placeholder: |
        If you're not sure of some details, don't worry! When we evaluate the feature request we may suggest modifications as necessary to work within the design constraints of MiMiC.
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      placeholder: Speficy any reference that might be used to get this feature done
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/raetro/community/blob/main/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
