################################################################################
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: OTHER
# SPDX-FileCopyrightText: (c) 2005-2021, The Raetro authors and contributors
################################################################################
name: "Bug Report"
description: "Let us know about an unexpected error, a crash, or an incorrect behavior."
title: 'Title of your Bug Report'
labels:
  - bug
assignees:
  - boogermann
body:
  - type: markdown
    attributes:
      value: |
        Hi there,

        Thank you for opening an issue. Please note that we try to keep the issue tracker reserved for bug reports and feature requests.
        Make sure to [search for existing issues](https://github.com/raetro/mimic_firmware/issues?q=label%3Abug) before filing a new one!

        For general usage questions, please visit the user guide at [Rætro.Docs](https://docs.raetro.org/mimic-nsx).

  - type: input
    id: version
    attributes:
      label: Version (or build number)
      placeholder: "0.1.1, 1.0.3-fb597ed"
      description: |
        You can find the version in the about dialog.

        If you are not running the latest version, please try upgrading because your issue may have already been fixed.
    validations:
      required: true

  - type: dropdown
    id: fpga
    attributes:
      label: What FPGA board are you seeing the problem on?
      multiple: false
      options:
        - Terasic DE10-Nano
        - Arrow DECA
        - Arrow/Trenz CYC1000
        - Trenz C10LP-REFKIT
        - NovTech Chameleon96

  - type: textarea
    id: app
    attributes:
      label: FPGA Core or Other Software
      description: If you're reporting a bug about MiMiC's interaction with an FPGA Core or another software, what FPGA Core/software? What versions?
      placeholder: |
        JTCPS2 (19691231)
        RetroArch v1.9.12
        My Awesome Game v0.3 (include a code snippet if it would help!)
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Please list the full steps required to reproduce the issue
      placeholder: |
        1. load core X
        2. load game Y into core X
        3. map joystick
    validations:
      required: false

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: If you want to include screenshots, paste them into the markdown editor below or follow up with a separate comment.
      placeholder: What were you expecting?
    validations:
      required: false

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Debug Output/Crash Output
      description: |
        Full debug output can be obtained by running MiMiC with UART or by setting the environment variable `MIMIC_LOG=trace`.
        Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.
        Share a link to a GitHub Gist containing the output of the `crash.log` file.
      placeholder: |
        https://gist.github.com/myuser/e6cb69a18488cbd420d5bafdd6bf0ba
    validations:
      required: false

  - type: textarea
    id: bug_context
    attributes:
      label: Additional Context
      description: |
        Are there anything atypical about your situation that we should know?
        For example: is MiMiC NSX running on an unsupported device? Are you passing any unusual command line options or using any environment variables?
    validations:
      required: false

  - type: textarea
    id: bug_config_file
    attributes:
      label: Configuration Files
      placeholder: |
        Paste the relevant parts of your MiMiC.ini configuration file.
    validations:
      required: false

  - type: input
    id: bug_firmware
    attributes:
      label: Opened Issues and Pull Requests
      placeholder: "#1234"
      description: |
        Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example: #1234
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/raetro/community/blob/main/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
