################################################################################
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: OTHER
# SPDX-FileCopyrightText: (c) 2021, The Raetro authors and contributors
################################################################################
name: "Question"
description: "Ask a question about MiMiC"
title: 'Title of your Question'
labels:
  - question
assignees:
  - boogermann
body:
  - type: markdown
    attributes:
      value: |
        Hi there,

        Please note that we try to keep the issue tracker reserved for bug reports and feature requests.
        Make sure to [search for existing questions](https://github.com/raetro/mimic_firmware/issues?q=label%3Aquestion) before filing a new one!

        For general usage questions, please visit the user guide at [Rætro.Docs](https://docs.raetro.org/mimic-nsx).

  - type: textarea
    id: question
    attributes:
      label: Ask a question about MiMiC
      placeholder: |
        Ask your question here! Please keep the questions related to MiMiC only.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/raetro/community/blob/main/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
